#pragma once

#include <windows.h>

constexpr const wchar_t* ADT_CONFIG_FILE_NAME = L"AntiDebugTimeline.ini";
constexpr const wchar_t* ADT_LOG_DIR_NAME = L"logs";
constexpr const wchar_t* ADT_LOG_FILE_NAME = L"AntiDebugTimeline.jsonl";

constexpr DWORD ADT_FEATURE_IS_DEBUGGER_PRESENT = 0x00000001;
constexpr DWORD ADT_FEATURE_CHECK_REMOTE_DEBUGGER_PRESENT = 0x00000002;
constexpr DWORD ADT_FEATURE_NT_QUERY_DEBUG_PORT = 0x00000004;
constexpr DWORD ADT_FEATURE_NT_QUERY_DEBUG_OBJECT = 0x00000008;
constexpr DWORD ADT_FEATURE_NT_QUERY_DEBUG_FLAGS = 0x00000010;
constexpr DWORD ADT_FEATURE_PEB_BEING_DEBUGGED = 0x00000020;
constexpr DWORD ADT_FEATURE_PEB_NT_GLOBAL_FLAG = 0x00000040;
constexpr DWORD ADT_FEATURE_OUTPUT_DEBUG_STRING = 0x00000080;
constexpr DWORD ADT_FEATURE_NT_SET_INFORMATION_THREAD = 0x00000100;
constexpr DWORD ADT_FEATURE_GET_THREAD_CONTEXT = 0x00000200;
constexpr DWORD ADT_FEATURE_PEB_HEAP_FLAGS = 0x00000400;

constexpr DWORD ADT_FEATURE_NT_QUERY_INFORMATION_PROCESS =
    ADT_FEATURE_NT_QUERY_DEBUG_PORT |
    ADT_FEATURE_NT_QUERY_DEBUG_OBJECT |
    ADT_FEATURE_NT_QUERY_DEBUG_FLAGS;

constexpr DWORD ADT_FEATURE_ALL =
    ADT_FEATURE_IS_DEBUGGER_PRESENT |
    ADT_FEATURE_CHECK_REMOTE_DEBUGGER_PRESENT |
    ADT_FEATURE_NT_QUERY_INFORMATION_PROCESS |
    ADT_FEATURE_PEB_BEING_DEBUGGED |
    ADT_FEATURE_PEB_NT_GLOBAL_FLAG |
    ADT_FEATURE_PEB_HEAP_FLAGS |
    ADT_FEATURE_OUTPUT_DEBUG_STRING |
    ADT_FEATURE_NT_SET_INFORMATION_THREAD |
    ADT_FEATURE_GET_THREAD_CONTEXT;
